# Generated by Django 5.2.3 on 2025-09-10 19:35

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prenda',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Prenda', 'verbose_name_plural': 'Prendas'},
        ),
        migrations.AlterModelOptions(
            name='seccion',
            options={'ordering': ['nombre'], 'verbose_name': 'Sección', 'verbose_name_plural': 'Secciones'},
        ),
        migrations.AlterModelOptions(
            name='subseccion',
            options={'ordering': ['nombre'], 'verbose_name': 'Subsección', 'verbose_name_plural': 'Subsecciones'},
        ),
        migrations.AlterModelOptions(
            name='subsubseccion',
            options={'ordering': ['nombre'], 'verbose_name': 'Subsubsección', 'verbose_name_plural': 'Subsubsecciones'},
        ),
        migrations.RemoveField(
            model_name='prenda',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='prenda',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='prenda',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='subseccion',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='subseccion',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='subsubseccion',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='subsubseccion',
            name='orden',
        ),
        migrations.AlterField(
            model_name='prenda',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='prendas/'),
        ),
        migrations.AlterField(
            model_name='subseccion',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='logos/subsecciones/'),
        ),
        migrations.AlterField(
            model_name='subsubseccion',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='logos/subsubsecciones/'),
        ),
    ]
