# Generated by Django 5.2.1 on 2025-09-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_equipacion_imagen_alter_equipo_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='equipaciones/'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='LogoEquipos/'),
        ),
        migrations.AlterField(
            model_name='liga',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='LogoLiga/'),
        ),
    ]
