# Generated by Django 5.2.3 on 2025-09-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_prenda_options_alter_seccion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='icono',
            field=models.CharField(blank=True, default='', help_text='Clase CSS del icono (ej: fas fa-tshirt)', max_length=50, null=True),
        ),
    ]
