# Generated by Django 5.2.3 on 2025-09-11 20:56

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_seccion_icono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='icono',
        ),
        migrations.AddField(
            model_name='seccion',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='logos/secciones/'),
        ),
    ]
